version: '3.8'

services:
  database:
    image: mongo:7.0.7-rc2-nanoserver-ltsc2022
    environment:
        MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
        MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
        MONGO_INITDB_DATABASE: ITA
    ports:
        - 27017:27017
    expose:
        - 27017
    volumes:
        - mongo_data:/data/db
    restart: unless-stopped

  mikroservice1:
        build: .
        restart: always
        ports:
            - 8080:8080
        expose:
            - 8080
        environment:
            - SPRING_PROFILES_ACTIVE=mongo
            - SPRING_DATA_MONGODB_URI=mongodb://database:27017/ITA
        depends_on:
            - database

