version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: jobsportal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haris123
    ports:
      - "5432:5432"
    networks:
      - backend

  microservice1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: microservice1
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    networks:
      - backend
      - activemq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/jobsportal
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=haris123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_ACTIVEMQ_BROKER_URL=tcp://activemq:61616

  activemq:
    image: rmohr/activemq:5.10.0
    container_name: activemq
    restart: unless-stopped
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - activemq

networks:
  activemq:
    driver: bridge
  backend:
    driver: bridge
